### ISSUE TITLE
Permission denied on android Q

### ISSUE THREAD

**Issue by weihangdong** [openstf/minitouch#41] opened 2019-03-15 09:00 UTC
i try on android Q，log：
Unable to open device /dev/input/event7 for inspectionopen: Permission denied
Unable to open device /dev/input/event6 for inspectionopen: Permission denied
Unable to open device /dev/input/event5 for inspectionopen: Permission denied
Unable to open device /dev/input/event1 for inspectionopen: Permission denied
Unable to open device /dev/input/event3 for inspectionopen: Permission denied
Unable to open device /dev/input/mice for inspectionopen: Permission denied
Unable to open device /dev/input/event0 for inspectionopen: Permission denied
Unable to open device /dev/input/event2 for inspectionopen: Permission denied
Unable to open device /dev/input/event4 for inspectionUnable to find a suitable touch device

not like stf#477 android Q has no "USB debugging (Security settings)"

**Comment by sorccu** [comment] 2019-03-16 08:05
After a brief investigation, it seems that while the shell user's permissions are unchanged:

```
sailfish:/ $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid) context=u:r:shell:s0
```

Even though the input device files still belong to the input group:

```
sailfish:/ $ ls -lah /dev/input
total 0
drwxr-xr-x  2 root root      220 1970-01-01 10:13 .
drwxr-xr-x 17 root root     3.9K 1970-01-01 10:13 ..
crw-rw----  1 root input 13,  64 1970-01-01 10:13 event0
crw-rw----  1 root input 13,  65 1970-01-01 10:13 event1
crw-rw----  1 root input 13,  66 1970-01-01 10:13 event2
crw-rw----  1 root input 13,  67 1970-01-01 10:13 event3
crw-rw----  1 root input 13,  68 1970-01-01 10:13 event4
crw-rw----  1 root input 13,  69 1970-01-01 10:13 event5
crw-rw----  1 root input 13,  70 1970-01-01 10:13 event6
crw-rw----  1 root input 13,  71 1970-01-01 10:13 event7
crw-rw----  1 root input 13,  63 1970-01-01 10:13 mice
```

SELinux is blocking minitouch from accessing them:

```
03-16 16:57:40.884 14606 14606 W minitouch: type=1400 audit(0.0:82): avc: denied { write } for name="event7" dev="tmpfs" ino=24637 scontext=u:r:shell:s0 tcontext=u:object_r:input_device:s0 tclass=chr_file permissive=0
```

There doesn't seem to be an obvious way around this issue. Note that Google has disabled access to the input devices in the past and then allowed it again in later betas. We'll see.

**Comment by thinkhy** [comment] 2019-03-16 14:24
Anyway, we can replace minitouch with a Java program which would simulate
keyboard event with accessbility APIs if Google persists to disallow to
access input files.

Simo Kinnunen <notifications@github.com> 于2019年3月16日周六 下午4:05写道：

**Comment by weihangdong** [comment] 2019-03-22 10:50
i want to replace minitouch with a jar，is there any reference？
i tried UiAutomation.injectInputEvent but it is unfriendly, and it has delay , cause action down and move not correct

**Comment by weihangdong** [comment] 2019-03-22 10:52
or any other suggestion？  thanks

**Comment by vliubezny** [comment] 2019-04-18 12:01
> ```
> # b/30861057: Shell access to existing input devices is an abuse
> # vector. The shell user can inject events that look like they
> # originate from the touchscreen etc.
> # Everyone should have already moved to UiAutomation#injectInputEvent
> # if they are running instrumentation tests (i.e. CTS), Monkey for
> # their stress tests, and the input command (adb shell input ...) for
> # injecting swipes and things.
> neverallow shell input_device:chr_file no_w_file_perms;
> ```
> From [AOSP sources](https://android.googlesource.com/platform/system/sepolicy/+/refs/tags/android-q-preview-2.5/public/shell.te)

In case of these restrictions won't be removed what are appropriate alternatives?
One possible solution is `adb shell input` like utility which injects event in system_server via IPC.
Would it be enough performant and flexible  as minitouch?

**Comment by alexazhou** [comment] 2019-08-08 06:03
I use google pixed 2 xl with Android Q beta6 ，also got premission denied

![image](https://user-images.githubusercontent.com/9353779/62678887-4a7f0b00-b9e5-11e9-92ca-8ebad7f4816a.png)

**Comment by varundtsfi** [comment] 2019-08-23 13:25
> I use google pixed 2 xl with Android Q beta6 ，also got premission denied
> 
> ![image](https://user-images.githubusercontent.com/9353779/62678887-4a7f0b00-b9e5-11e9-92ca-8ebad7f4816a.png)

Hi @alexazhou @sorccu 

I was also getting the same logs e.g:
**Unable to open device /dev/input/event1 for inspectionopen: Permission denied 
Unable to open device /dev/input/event2 for inspectionopen: Permission denied**

But as @sorccu  earlier mentioned **SELinux is blocking minitouch(wrapper on libedev) from accessing them** and Google has disabled access to the input devices in the past and then allowed it again in later betas. We'll see.
I think in android 10 beta third party libs are not supported.

But for now I have found a solution. We can use android standard API to handle the touch events. And there are very less chances that android may depreciate these services.

**https://developer.android.com/reference/android/view/MotionEvent.html**

By the above implementation I am able to handle the touch events and its working fine and smoothly.

@sorccu  What is your opinion sir on this?

**Comment by nghiadhd** [comment] 2019-08-31 17:15
@varundtsfi 
To support MotionEvent, we must build a small server and start it by instrument. 
https://www.softteco.com/blog/touch-hold-swipe-release-gesture-simulation-in-android-unit-test/

It will take a lot of time to support like minitouch. Otherwise, I'm having concern about performance. The minitouch has great performance.
Hope the Googe will open libedev again

**Comment by varundtsfi** [comment] 2019-09-07 18:07
> @varundtsfi
> To support MotionEvent, we must build a small server and start it by instrument.
> https://www.softteco.com/blog/touch-hold-swipe-release-gesture-simulation-in-android-unit-test/
> 
> It will take a lot of time to support like minitouch. Otherwise, I'm having concern about performance. The minitouch has great performance.
> Hope the Googe will open libedev again

Hi @nghiadhd 

I have build Android 10  **QP1A.190711.020 | android-10.0.0_r2** but result is same. Google has disabled access to the input devices (libedev). 

I have small server inside the openstf service.
https://github.com/openstf/STFService.apk

Now your concern about the performance is correct but I am using my device remotely and it's working fine. If I compare this with minitouch(Wrapper over libedev), difference is very less. Locally you can not feel and remotely It's very less. You can try once and check the performance.

**Comment by varundtsfi** [comment] 2019-09-07 18:10
> After a brief investigation, it seems that while the shell user's permissions are unchanged:
> 
> ```
> sailfish:/ $ id
> uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid) context=u:r:shell:s0
> ```
> 
> Even though the input device files still belong to the input group:
> 
> ```
> sailfish:/ $ ls -lah /dev/input
> total 0
> drwxr-xr-x  2 root root      220 1970-01-01 10:13 .
> drwxr-xr-x 17 root root     3.9K 1970-01-01 10:13 ..
> crw-rw----  1 root input 13,  64 1970-01-01 10:13 event0
> crw-rw----  1 root input 13,  65 1970-01-01 10:13 event1
> crw-rw----  1 root input 13,  66 1970-01-01 10:13 event2
> crw-rw----  1 root input 13,  67 1970-01-01 10:13 event3
> crw-rw----  1 root input 13,  68 1970-01-01 10:13 event4
> crw-rw----  1 root input 13,  69 1970-01-01 10:13 event5
> crw-rw----  1 root input 13,  70 1970-01-01 10:13 event6
> crw-rw----  1 root input 13,  71 1970-01-01 10:13 event7
> crw-rw----  1 root input 13,  63 1970-01-01 10:13 mice
> ```
> 
> SELinux is blocking minitouch from accessing them:
> 
> ```
> 03-16 16:57:40.884 14606 14606 W minitouch: type=1400 audit(0.0:82): avc: denied { write } for name="event7" dev="tmpfs" ino=24637 scontext=u:r:shell:s0 tcontext=u:object_r:input_device:s0 tclass=chr_file permissive=0
> ```
> 
> There doesn't seem to be an obvious way around this issue. Note that Google has disabled access to the input devices in the past and then allowed it again in later betas. We'll see.

Hi @sorccu 
I have build with the Latest android release **QP1A.190711.020 | android-10.0.0_r2** and tried minituch but Its not allowing. I think Google has disabled the access to the input devices.

**Comment by hkivela** [comment] 2019-09-16 13:32
@sorccu some work on using protobuf to send motion events: https://github.com/hkivela/STFService.apk/commit/b127aaf314cb22af0db4c30c4a845093ec392943

It is similar to minitouch approach. This is missing pointer id setting and pressure though. Works on Android 10 without rooting.

**Comment by stoefln** [comment] 2019-12-20 10:59
Any update on this?

**Comment by lycfr** [comment] 2020-02-26 05:54
Any update on this?

**Comment by stoefln** [comment] 2020-02-26 10:00
Isn't this issue a duplicate of https://github.com/openstf/minitouch/issues/49
For me minitouch works with Android Q now

**Comment by koral--** [comment] 2020-02-26 15:28
Indeed it looks like the same issue.

**Closed as completed by koral--** 2020-02-26 15:28 UTC
